version: '3'
services:
  dataimporter:
    build: .
    links:
    - postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
